allowBuilds:
  '@parcel/watcher': true
  core-js: set this to true or false
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild

packages:
  - 'packages/*'
