#!/usr/bin/env sh
set -e

BLUE='\033[34m'
GREEN='\033[32m'
RESET='\033[39m'


printf "\n${BLUE}---------------------${RESET}\n"
printf "${BLUE}Step 1: pnpm run lint${RESET}\n"
printf "${BLUE}---------------------${RESET}\n"


start_time=$(date +%s)
pnpm run lint
end_time=$(date +%s)
elapsed_time=$((end_time - start_time))

printf "\n${GREEN}eslint took %s seconds${RESET}\n" "$elapsed_time"

printf "\n${BLUE}---------------------------${RESET}\n"
printf "${BLUE}Step 2: pnpm run lint:biome${RESET}\n"
printf "${BLUE}---------------------------${RESET}\n"

pnpm run lint:biome

# ------------------------------------------------------------

printf "\n${GREEN}All lint checks passed!${RESET}\n\n"
